qwen_api_chat:
  qwen2:
    - 1.5b-instruct
    - 0.5b-instruct
  qwen1.5:
    - 1.8b-chat
    - 0.5b-chat

baidu_api_chat:
  ernie-speed:
    - ernie_speed
    - ernie-speed-128k
  ernie-lite:
    - eb-instant
    - ernie-lite-8k
  ernie-tiny:
    - ernie-tiny-8k
  other:
    - yi_34b_chat

local_chat:
  model_dict:
    qwen:
      - 1.5B
      - 7B
    llama3:
      - 8B
  name2path:
    qwen-1.5B: /home/pandas/snap/model/QwenQwen2-1.5B-Instruct
    qwen-7B: /home/pandas/snap/model/QwenQwen2-7B-Instruct-AWQ
    llama3-8b: /home/pandas/snap/model/Llama3-8B-Chinese-Chat
  max_history_len: 6
  max_output_len: 512



rag:
  max_rag_len: 3000
  rag_info_name:
    - 决策的艺术
  decision:
    database_name: '/home/pandas/snap/code/RapidOcr/database_data/data/decision_making'
    table_name: 'decision'
    model_path: '/home/pandas/snap/model/Dmeta-embedding-zh'
    top_k: 3

ui_conf:
  default_system: 'You are a helpful assistant.'

video:
  root_dir: '/media/pandas/video/video'
  mark_csv_path: '/home/pandas/snap/code/RapidOcr/database_data/data/adult_video/movie_mark.csv'
  hobby_tag:
    high_heel: 高根
    silk_stockings: 丝袜
    maid_outfit: 女仆装
    school_uniform: 学生装
    office_lady: ol
    large_bust: 巨乳
    medium_bust: 中乳
    small_bust: 小乳
    multi_person: 多人
    erotic: 情趣
    chinese_subtitles: 中字

ocr:
  font_path: '/home/pandas/snap/code/RapidOcr/ocr/font/SimHei.ttf'