qwen_api_chat:
  qwen2:
    - 1.5b-instruct
    - 0.5b-instruct
  qwen1.5:
    - 1.8b-chat
    - 0.5b-chat

baidu_api_chat:
  ernie-speed:
    - ernie_speed
    - ernie-speed-128k
  ernie-lite:
    - eb-instant
    - ernie-lite-8k
  ernie-tiny:
    - ernie-tiny-8k
  other:
    - yi_34b_chat

local_chat:
  model_dict:
    qwen2.5:
      - 7B-Instruct
      - 7B-Instruct-AWQ
      - 1.5-Instruct-Coder
      - 7B-Coder
    qwen2:
      - 1.5B-Instruct
      - 7B-Instruct-AWQ
    llama3:
      - 8B
    MiniCPM3:
      - 4B
  name2path:
    qwen2.5-7B-Instruct: /home/pandas/snap/model/qwen/qwen2.5-7b-instruct
    qwen2.5-7B-Instruct-AWQ: /home/pandas/snap/model/qwen/Qwen2-7B-Instruct-AWQ
    qwen2.5-1.5-Instruct-Coder: /home/pandas/snap/model/qwen/Qwen2.5-Coder-1.5B-Instruct
    qwen2.5-7B-Coder: /home/pandas/snap/model/qwen/Qwen2.5-Coder-7B
    qwen2-1.5B-Instruct: /home/pandas/snap/model/qwen/Qwen2-1.5B-Instruct
    qwen2-7B-Instruct-AWQ: /home/pandas/snap/model/qwen/Qwen2-7B-Instruct-AWQ
    llama3-8b: /home/pandas/snap/model/Llama3-8B-Chinese-Chat
    MiniCPM3-4B: /home/pandas/snap/model/MiniCPM3-4B
    StepfunOcr: /home/pandas/snap/model/stepfun-aiGOT-OCR2_0
  max_history_len: 6
  max_output_len: 512



rag:
  max_rag_len: 3000
  rag_info_name:
    - 决策的艺术
    - 
  decision:
    database_name: '/home/pandas/snap/code/RapidOcr/database_data/data/decision_making'
    table_name: 'decision'
    model_path: '/home/pandas/snap/model/bge-small-zh-v1.5'
    model_name: 'bge_small'
    top_k: 3

ui_conf:
  default_system: 'You are a helpful assistant.'

video:
  root_dir: '/media/pandas/video/video'
  mark_csv_path: '/home/pandas/snap/code/RapidOcr/database_data/data/adult_video/movie_mark.csv'
  breast_size:
    - 巨乳
    - 中乳
    - 小乳
  start_score:
    - 1分
    - 2分
    - 3分
    - 4分
    - 5分
  clothing:
    high_heel: 高根
    silk_stockings: 丝袜
    maid_outfit: 女仆装
    school_uniform: 学生装
    office_lady: ol
    erotic: 情趣
  action:
    oral_sex: 口交
    breast_sex: 乳交
    doggy_style: 后入
    missionary_position: 前入
    lotus_position: 坐莲
    foreplay: 前戏
  scene:
    office: 办公室
    school: 学校
    bubble_bath: 泡泡浴
    adult_entertainment_establishment: 风俗店
    home: 家里
    hotel: 酒店
    photography_studio: 拍摄棚
    Bathroom: 卫生间
    washroom: 浴室
    outdoorL: 户外
  other:
    multi_person: 多人
    chinese_subtitles: 中字
    tiktok: 抖音
    invasion: 侵犯
    first_person_perspective: 第一视角
    infidelity: 出轨
    uncensored: 无码

ocr:
  font_path: '/home/pandas/snap/code/RapidOcr/ocr/font/SimHei.ttf'