local_chat:
  model_dict:
    qwen2.5:
      - 0.5B-Instruct
  max_history_len: 6
  max_output_len: 4096
  qwen_support:
    - qwen2.5-7B-Instruct
    - qwen2.5-7B-Instruct-AWQ
    - qwen2.5-1.5-Instruct-Coder
    - qwen2.5-7B-Coder
    - qwen2-1.5B-Instruct
    - qwen2-7B-Instruct-AWQ
    - qwen2.5-3B-Instruct
    - qwen2.5-0.5B-Instruct
    - deepseek-7B
    - deepseek-1.5B

rag:
  database:
    choise: 'lancedb'
    lancedb:
      save:
        database_dir: 'data'
        articles_user_path: 'user_article_mapping.json'
        kb_article_map_path: 'kb_article_mappping.json'
    milvus:
      save:
        articles_user_path: 'user_article_mapping.json'
        kb_article_map_path: 'kb_article_mappping.json'
  parse_voice:
    voice_chunk_size: 1024
  top_k: 10
  max_rag_len: 10000


user:
  user_password_info_dict_path: 'auth.json'

ui_conf:
  default_system: 'You are a helpful assistant.'

video:
  root_dir: '/media/pandas/video/video'
  breast_size:
    - 巨乳
    - 中大
    - 中乳
    - 中小
    - 小乳
  start_score:
    - 1分
    - 2分
    - 2.5分
    - 3分
    - 3.5分
    - 4分
    - 5分
  clothing:
    high_heel: 高根
    silk_stockings: 丝袜
    maid_outfit: 女仆装
    school_uniform: 学生装
    office_lady: ol
    erotic: 情趣
    bunny_girl: 兔女郎
    daily_clothes: 常服
  action:
    oral_sex: 口交
    breast_sex: 乳交
    doggy_style: 后入
    missionary_position: 前入
    lotus_position: 坐莲
    foreplay: 前戏
  scene:
    office: 办公室
    school: 学校
    bubble_bath: 泡泡浴
    adult_entertainment_establishment: 风俗店
    home: 家里
    hotel: 酒店
    photography_studio: 拍摄棚
    Bathroom: 卫生间
    washroom: 浴室
    outdoorL: 户外
  other:
    multi_person: 多人
    chinese_subtitles: 中字
    tiktok: 抖音
    invasion: 侵犯
    first_person_perspective: 第一视角
    infidelity: 出轨
    uncensored: 无码
    housewife: 人妻
    transparent: 透明