local_chat:
  model_dict:
    deepseek:
#      - 7B
      - 1.5B
    qwen2.5:
      - 7B-Instruct
      - 7B-Instruct-AWQ
      - 1.5-Instruct-Coder
      - 7B-Coder
      - 3B-Instruct
      - 0.5B-Instruct
    qwen2:
      - 1.5B-Instruct
      - 7B-Instruct-AWQ
    llama3:
      - 8B
    MiniCPM3:
      - 4B
    百度:
      - ernie_speed
      - ernie-speed-128k
      - eb-instant
      - ernie-lite-8k
      - ernie-tiny-8k
    零一万物:
      - yi_34b_chat
    阿里在线:
      - 1.5b-instruct
      - 0.5b-instruct
      - 1.8b-chat
      - 0.5b-chat
  name2path:
    qwen2.5-7B-Instruct: C:\use\model\qwen2.5-7b-instruct
    qwen2.5-7B-Instruct-AWQ: C:\use\model\QwenQwen2.5-7B-Instruct-AWQ
#    qwen2.5-1.5-Instruct-Coder: /home/pandas/snap/model/qwen/Qwen2.5-Coder-1.5B-Instruct
#    qwen2.5-7B-Coder: /home/pandas/snap/model/qwen/Qwen2.5-Coder-7B
#    qwen2-1.5B-Instruct: /home/pandas/snap/model/qwen/Qwen2-1.5B-Instruct
#    qwen2-7B-Instruct-AWQ: /home/pandas/snap/model/qwen/Qwen2-7B-Instruct-AWQ
#    qwen2.5-3B-Instruct: /home/pandas/snap/model/qwen/qwen2.5-3b-instruct
    qwen2.5-0.5B-Instruct: C:\use\model\Qwen25_05B_Instruct
#    llama3-8b: /home/pandas/snap/model/Llama3-8B-Chinese-Chat
#    MiniCPM3-4B: /home/pandas/snap/model/MiniCPM3-4B
    StepfunOcr: C:\use\model\stepfun-aiGOT-OCR2_0
#    deepseek-7B: /home/pandas/snap/model/deepseek/deepseek_r1_distill_qwen_7b
    deepseek-1.5B: C:\use\model\deepseek_r1_distill_qwen_1_5b
  max_history_len: 6
  max_output_len: 4096
  qwen_support:
    - qwen2.5-7B-Instruct
    - qwen2.5-7B-Instruct-AWQ
    - qwen2.5-1.5-Instruct-Coder
    - qwen2.5-7B-Coder
    - qwen2-1.5B-Instruct
    - qwen2-7B-Instruct-AWQ
    - qwen2.5-3B-Instruct
    - qwen2.5-0.5B-Instruct
#    - deepseek-7B
    - deepseek-1.5B
  multimodal:
    model_path: 'C:\use\model\openbmbMiniCPM-V-2_6-int4'

rag:
  database:
    choise: 'lancedb'
    lancedb:
      save:
        database_dir: 'C:\use\code\RapidOcr_small\data\database\lancedb\data'
        articles_user_path: 'C:\use\code\RapidOcr_small\data\database\lancedb\user_article_mapping.json'
        kb_article_map_path: 'C:\use\code\RapidOcr_small\data\database\lancedb\kb_article_mappping.json'
    milvus:
      save:
        articles_user_path: 'C:\use\code\RapidOcr_small\data\database\milvus\user_article_mapping.json'
        kb_article_map_path: 'C:\use\code\RapidOcr_small\data\database\milvus\kb_article_mappping.json'
  embedding_mdoel:
    bge_m3:
      model_path: 'C:\use\model\BAAIbge-m3'
  parse_voice:
    model_path: '/home/pandas/snap/model/FireRedASR-AED-L'
    voice_chunk_size: 1024
  parse_image:
    model_path: '/home/pandas/snap/model/stepfun-aiGOT-OCR2_0'
  tokenizer:
    trie_dir_path: 'C:\use\code\RapidOcr_small\data\res'
  top_k: 10
  max_rag_len: 10000
  rag_data_csv_dir: 'C:\use\code\RapidOcr_small\data\rag\data_csv'
  tmp_dir_path: 'C:\use\code\RapidOcr_small\data\tmp'


user:
  user_password_info_dict_path: 'C:\use\code\RapidOcr_small\config\auth.json'

ui_conf:
  default_system: 'You are a helpful assistant.'

video:
  root_dir: 'D:\video'
  cut_save_dir: 'D:\video\cur_video'
  cut_record_path: 'C:\use\code\RapidOcr_small\data\adult_video\video_cut_record.txt'
  mark_csv_path: 'C:\use\code\RapidOcr_small\data\adult_video\movie_mark.csv'
  translation_title_csv_path: 'C:\use\code\RapidOcr_small\data\translation\translation.csv'
  need_translation_title_path: 'C:\use\code\RapidOcr_small\data\translation\need_translation.txt'
  breast_size:
    - 巨乳
    - 中大
    - 中乳
    - 中小
    - 小乳
  start_score:
    - 1分
    - 2分
    - 2.5分
    - 3分
    - 3.5分
    - 4分
    - 5分
  clothing:
    high_heel: 高根
    silk_stockings: 丝袜
    maid_outfit: 女仆装
    school_uniform: 学生装
    office_lady: ol
    erotic: 情趣
    bunny_girl: 兔女郎
    daily_clothes: 常服
  action:
    oral_sex: 口交
    breast_sex: 乳交
    doggy_style: 后入
    missionary_position: 前入
    lotus_position: 坐莲
    foreplay: 前戏
  scene:
    office: 办公室
    school: 学校
    bubble_bath: 泡泡浴
    adult_entertainment_establishment: 风俗店
    home: 家里
    hotel: 酒店
    photography_studio: 拍摄棚
    Bathroom: 卫生间
    washroom: 浴室
    outdoorL: 户外
  other:
    multi_person: 多人
    chinese_subtitles: 中字
    tiktok: 抖音
    invasion: 侵犯
    first_person_perspective: 第一视角
    infidelity: 出轨
    uncensored: 无码
    housewife: 人妻
    transparent: 透明
ocr:
  font_path: 'C:\use\code\RapidOcr_small\data\ocr\font\SimHei.ttf'