local_chat:
  max_history_len: 6
  max_output_len: 10240
  qwen_support:
    - qwen2.5-7B-Instruct
    - qwen2.5-0.5B-Instruct
    - deepseek-1.5B

rag:
  database:
    choise: 'lancedb'
    lancedb:
      save:
        database_dir: 'data'
        articles_user_path: 'user_article_mapping.json'
        kb_article_map_path: 'kb_article_mappping.json'
    milvus:
      save:
        articles_user_path: 'user_article_mapping.json'
        kb_article_map_path: 'kb_article_mappping.json'
  parse_voice:
    voice_chunk_size: 1024
  top_k: 10
  max_rag_len: 10000


user:
  user_password_info_dict_path: 'auth.json'

ui_conf:
  default_system: 'You are a helpful assistant.'


mysql:
  host: 'localhost'
  user: 'root'
  password: 'root'
  port: 3310
  database_name: 'gradio_bot'
  article_table_name: 'article_info'