# 使用 PyTorch 2.4.1 的 GPU 运行时镜像作为基础镜像
FROM pytorch/pytorch:2.4.1-cuda12.4-cudnn9-runtime

# 设置工作目录
WORKDIR /app

# 安装系统级依赖
RUN apt-get update && apt-get install -y \
    build-essential \
    wget \
    vim \
    curl \
    procps \
    && rm -rf /var/lib/apt/lists/*

# 复制 requirements.txt 文件到工作目录
COPY ./requirements.txt .

# 安装 requirements.txt 中的 Python 依赖
RUN pip install --no-cache-dir -r requirements.txt -i https://pypi.tuna.tsinghua.edu.cn/simple

# 下载 wheel 文件
RUN wget http://thunlp.oss-cn-qingdao.aliyuncs.com/multi_modal/never_delete/modelscope_studio-0.4.0.9-py3-none-any.whl

# 安装 wheel 文件
RUN pip install --no-cache-dir modelscope_studio-0.4.0.9-py3-none-any.whl

# 暴露端口（假设你的应用监听 7680 端口，可按需修改）
EXPOSE 7680    